server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update

logging.level.ru.alfa.test.core: DEBUG

link:
  type:path: ${TYPE_PATH:}